### PR TITLE
terminal-flat-theme 2.0.0

### LINKED ISSUE #6: Cannot get it to work on Ubuntu 15.04
Hi there! :)

I just installed the latest ubuntu on my computer, added your beautiful Flattiance theme and tried the flat terminal theme but with no success.

I tried both methods: npm and cloning but it doesn't change anything in the terminal

may be I'm missing something... :)

### PR DESCRIPTION
**Pull request by IonicaBizau**
It was the time to push some new updates in this project! :hourglass: 

In this pull request I'm adding multiple terminal compatibility, provided by [this nice tool](http://terminal.sexy/#FSIvLsxxNEle50w8Gryc85wSNJjbm1m28cQP7PDxLD5QwDkrFqCFlaWmKYC5jkStJ65glaWm). :star2: 

This also fixes #6–adding compatibility with the latest changes (and maybe latest bugs) in gconftool2. Now it creates a new profile (at least in Gnome Terminal) which you have to manually select and then automagically enjoy. :smile: 

@iRaul Can you please test the iTerm theme (schemes/iterm.xml)? Thanks! :green_apple:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@iRaul Can you please give feedback on this? :bell:

**Comment by IonicaBizau** [comment]
@iRaul I investigated why the previous version didn't work for you. I speculate it was because of the tabs vs spaces thingy. Now the iTerm scheme contains tabs and should work for you too. :smile:

**Comment by iRaul** [comment]
Sound`s good @IonicaBizau! Now we can test this theme without no hacks :smile:

**Comment by IonicaBizau** [comment]
@iRaul Yeah! :grimacing: If you like to improve the colors, there is always something to improve. Contributions are more than welcome! :sparkle:

**Comment by iRaul** [comment]
@IonicaBizau Sure, I would love to!

**Pull request merged**
